spring.application.name=projet
spring.batch.retriever=false
spring.batch.archive=data/archive/
spring.batch.pathFile=data/csvFile
spring.batch.bilanDir=data/bilan/
spring.batch.csvFileLoc=data/csvFile/adresses.csv
spring.batch.gzFilePath=data/FichierGz/adresses.csv.gz
spring.batch.urlPathFile=https://adresse.data.gouv.fr/data/ban/adresses/latest/csv/adresses-79.csv.gz

# API REST
spring.main.web-application-type=servlet


# Desactive le lancement automatique du job au demarrage
spring.batch.job.enabled=false

# Initialise automatiquement le schema de metadonnees Spring Batch
spring.batch.jdbc.initialize-schema=always
spring.sql.init.mode=always

#### VEUILLEZ COMMENTER LA BASE QUI N'EST PAS UTILISE ###

# -------------------------
# SQLite
 -------------------------
#spring.profiles.active=sqlite
#spring.datasource.url=jdbc:sqlite:adresse.db
#spring.datasource.driver-class-name=org.sqlite.JDBC
#spring.sql.init.schema-locations=classpath:schema_sqlite.sql
#spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
#spring.datasource.hikari.maximum-pool-size=1
#workerSize=1

# -------------------------
# POSTGRES
# -------------------------
spring.profiles.active=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/adresse
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.schema-locations=classpath:schema_postgres.sql
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.datasource.hikari.maximum-pool-size=30
workerSize=8

##########################################################


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.devtools.restart.enabled=false
logging.level.org.springframework.batch=DEBUG
logging.level.org.springframework.batch.core.repository=DEBUG
logging.level.org.springframework.jdbc.datasource=DEBUG