CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE TABLE IF NOT EXISTS adresse (
                                       id TEXT,
                                       id_fantoir TEXT,
                                       numero TEXT,
                                       rep TEXT,
                                       nom_voie TEXT,
                                       code_postal TEXT,
                                       code_insee TEXT,
                                       nom_commune TEXT,
                                       code_insee_ancienne_commune TEXT,
                                       nom_ancienne_commune TEXT,
                                       x DOUBLE PRECISION,
                                       y DOUBLE PRECISION,
                                       lon DOUBLE PRECISION,
                                       lat DOUBLE PRECISION,
                                       type_position TEXT,
                                       alias TEXT,
                                       nom_ld TEXT,
                                       libelle_acheminement TEXT,
                                       nom_afnor TEXT,
                                       source_position TEXT,
                                       source_nom_voie TEXT,
                                       certification_commune INTEGER,
                                       cad_parcelles TEXT,
                                       search_text text,
                                       CONSTRAINT uk_adresse UNIQUE (id, type_position, x, y)
    );

CREATE TABLE IF NOT EXISTS adresse_staging (
                                               id TEXT,
                                               id_fantoir TEXT,
                                               numero TEXT,
                                               rep TEXT,
                                               nom_voie TEXT,
                                               code_postal TEXT,
                                               code_insee TEXT,
                                               nom_commune TEXT,
                                               code_insee_ancienne_commune TEXT,
                                               nom_ancienne_commune TEXT,
                                               x DOUBLE PRECISION,
                                               y DOUBLE PRECISION,
                                               lon DOUBLE PRECISION,
                                               lat DOUBLE PRECISION,
                                               type_position TEXT,
                                               alias TEXT,
                                               nom_ld TEXT,
                                               libelle_acheminement TEXT,
                                               nom_afnor TEXT,
                                               source_position TEXT,
                                               source_nom_voie TEXT,
                                               certification_commune INTEGER,
                                               cad_parcelles TEXT
);

CREATE TABLE IF NOT EXISTS BATCH_JOB_INSTANCE (
    JOB_INSTANCE_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT,
    JOB_NAME VARCHAR(100) NOT NULL,
    JOB_KEY VARCHAR(32) NOT NULL,
    CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
);

CREATE TABLE IF NOT EXISTS DVF (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    ID_MUTATION VARCHAR(255),
    DATE_MUTATION DATE,
    NUMERO_DISPOSITION INTEGER,
    NATURE_MUTATION VARCHAR(100),
    VALEUR_FONCIERE DECIMAL(19, 2),
    ADRESSE_NUMERO VARCHAR(20),
    ADRESSE_SUFFIXE VARCHAR(10),
    ADRESSE_CODE_VOIE VARCHAR(4),
    ADRESSE_NOM_VOIE VARCHAR(255),
    CODE_POSTAL VARCHAR(5),
    CODE_COMMUNE VARCHAR(5),
    NOM_COMMUNE VARCHAR(255),
    ANCIEN_CODE_COMMUNE VARCHAR(5),
    ANCIEN_NOM_COMMUNE VARCHAR(255),
    CODE_DEPARTEMENT VARCHAR(3),
    ID_PARCELLE VARCHAR(14),
    ANCIEN_ID_PARCELLE VARCHAR(14),
    NUMERO_VOLUME VARCHAR(20),
    LOT_1_NUMERO VARCHAR(20),
    LOT_1_SURFACE_CARREZ DECIMAL(19, 2),
    LOT_2_NUMERO VARCHAR(20),
    LOT_2_SURFACE_CARREZ DECIMAL(19, 2),
    LOT_3_NUMERO VARCHAR(20),
    LOT_3_SURFACE_CARREZ DECIMAL(19, 2),
    LOT_4_NUMERO VARCHAR(20),
    LOT_4_SURFACE_CARREZ DECIMAL(19, 2),
    LOT_5_NUMERO VARCHAR(20),
    LOT_5_SURFACE_CARREZ DECIMAL(19, 2),
    NOMBRE_LOTS INTEGER,
    CODE_TYPE_LOCAL VARCHAR(10),
    TYPE_LOCAL VARCHAR(100),
    SURFACE_REELLE_BATI DECIMAL(19, 2),
    NOMBRE_PIECES_PRINCIPALES INTEGER,
    CODE_NATURE_CULTURE VARCHAR(10),
    NATURE_CULTURE VARCHAR(100),
    CODE_NATURE_CULTURE_SPECIALE VARCHAR(10),
    NATURE_CULTURE_SPECIALE VARCHAR(100),
    SURFACE_TERRAIN DECIMAL(19, 2),
    LONGITUDE DECIMAL(12, 8),
    LATITUDE DECIMAL(12, 8)
);

CREATE TABLE IF NOT EXISTS dvf_staging (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    ID_MUTATION VARCHAR(255),
    DATE_MUTATION DATE,
    NUMERO_DISPOSITION INTEGER,
    NATURE_MUTATION VARCHAR(100),
    VALEUR_FONCIERE DECIMAL(19, 2),
    ADRESSE_NUMERO VARCHAR(20),
    ADRESSE_SUFFIXE VARCHAR(10),
    ADRESSE_CODE_VOIE VARCHAR(4),
    ADRESSE_NOM_VOIE VARCHAR(255),
    CODE_POSTAL VARCHAR(5),
    CODE_COMMUNE VARCHAR(5),
    NOM_COMMUNE VARCHAR(255),
    ANCIEN_CODE_COMMUNE VARCHAR(5),
    ANCIEN_NOM_COMMUNE VARCHAR(255),
    CODE_DEPARTEMENT VARCHAR(3),
    ID_PARCELLE VARCHAR(14),
    ANCIEN_ID_PARCELLE VARCHAR(14),
    NUMERO_VOLUME VARCHAR(20),
    LOT_1_NUMERO VARCHAR(20),
    LOT_1_SURFACE_CARREZ DECIMAL(19, 2),
    LOT_2_NUMERO VARCHAR(20),
    LOT_2_SURFACE_CARREZ DECIMAL(19, 2),
    LOT_3_NUMERO VARCHAR(20),
    LOT_3_SURFACE_CARREZ DECIMAL(19, 2),
    LOT_4_NUMERO VARCHAR(20),
    LOT_4_SURFACE_CARREZ DECIMAL(19, 2),
    LOT_5_NUMERO VARCHAR(20),
    LOT_5_SURFACE_CARREZ DECIMAL(19, 2),
    NOMBRE_LOTS INTEGER,
    CODE_TYPE_LOCAL VARCHAR(10),
    TYPE_LOCAL VARCHAR(100),
    SURFACE_REELLE_BATI DECIMAL(19, 2),
    NOMBRE_PIECES_PRINCIPALES INTEGER,
    CODE_NATURE_CULTURE VARCHAR(10),
    NATURE_CULTURE VARCHAR(100),
    CODE_NATURE_CULTURE_SPECIALE VARCHAR(10),
    NATURE_CULTURE_SPECIALE VARCHAR(100),
    SURFACE_TERRAIN DECIMAL(19, 2),
    LONGITUDE DECIMAL(12, 8),
    LATITUDE DECIMAL(12, 8)
);

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT,
    JOB_INSTANCE_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    START_TIME TIMESTAMP DEFAULT NULL,
    END_TIME TIMESTAMP DEFAULT NULL,
    STATUS VARCHAR(10),
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED TIMESTAMP,
    CONSTRAINT JOB_INST_EXEC_FK
        FOREIGN KEY (JOB_INSTANCE_ID)
        REFERENCES BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
);

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_PARAMS (
    JOB_EXECUTION_ID BIGINT NOT NULL,
    PARAMETER_NAME VARCHAR(100) NOT NULL,
    PARAMETER_TYPE VARCHAR(100) NOT NULL,
    PARAMETER_VALUE VARCHAR(2500),
    IDENTIFYING CHAR(1) NOT NULL,
    CONSTRAINT JOB_EXEC_PARAMS_FK
        FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT NOT NULL,
    STEP_NAME VARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    START_TIME TIMESTAMP DEFAULT NULL,
    END_TIME TIMESTAMP DEFAULT NULL,
    STATUS VARCHAR(10),
    COMMIT_COUNT BIGINT,
    READ_COUNT BIGINT,
    FILTER_COUNT BIGINT,
    WRITE_COUNT BIGINT,
    READ_SKIP_COUNT BIGINT,
    WRITE_SKIP_COUNT BIGINT,
    PROCESS_SKIP_COUNT BIGINT,
    ROLLBACK_COUNT BIGINT,
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED TIMESTAMP,
    CONSTRAINT JOB_EXEC_STEP_FK
        FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION_CONTEXT (
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    CONSTRAINT STEP_EXEC_CTX_FK
        FOREIGN KEY (STEP_EXECUTION_ID)
        REFERENCES BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
);

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_CONTEXT (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    CONSTRAINT JOB_EXEC_CTX_FK
        FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

CREATE TABLE IF NOT EXISTS tarif_commune (
    id BIGINT GENERATED ALWAYS AS IDENTITY,

    code_insee VARCHAR(5) NOT NULL,

    -- Indicateurs de la période N
    prix_moyen NUMERIC(15, 2),
    prix_median NUMERIC(15, 2),
    prix_m2 NUMERIC(15, 2),
    nombre_transactions BIGINT NOT NULL DEFAULT 0,

    -- Indicateurs de la période N-1
    prix_moyen_n_1 NUMERIC(15, 2),
    prix_median_n_1 NUMERIC(15, 2),
    prix_m2_n_1 NUMERIC(15, 2),
    nombre_transactions_n_1 BIGINT NOT NULL DEFAULT 0,

    -- Variations entre N et N-1, en pourcentage
    variation_prix_moyen_pct NUMERIC(10, 2),
    variation_prix_median_pct NUMERIC(10, 2),
    variation_prix_m2_pct NUMERIC(10, 2),
    variation_nombre_transactions_pct NUMERIC(10, 2),

    -- Bornes temporelles utilisées pour le calcul
    date_debut_periode_n DATE NOT NULL,
    date_fin_periode_n DATE NOT NULL,
    date_debut_periode_n_1 DATE NOT NULL,
    date_fin_periode_n_1 DATE NOT NULL,

    -- Date de dernière exécution du calcul
    date_calcul TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
    CONSTRAINT ck_tarif_commune_code_insee CHECK (code_insee::text ~ '^[0-9A-Z]{5}$'::text),
    CONSTRAINT ck_tarif_commune_periode_n CHECK (date_debut_periode_n < date_fin_periode_n),
    CONSTRAINT ck_tarif_commune_periode_n_1 CHECK (date_debut_periode_n_1 < date_fin_periode_n_1),
    CONSTRAINT ck_tarif_commune_periodes_successives CHECK ((date_fin_periode_n_1 + 1) = date_debut_periode_n),
    CONSTRAINT ck_tarif_commune_prix_m2 CHECK (prix_m2 IS NULL OR prix_m2 > 0::numeric),
    CONSTRAINT ck_tarif_commune_prix_m2_n_1 CHECK (prix_m2_n_1 IS NULL OR prix_m2_n_1 > 0::numeric),
    CONSTRAINT ck_tarif_commune_prix_median CHECK (prix_median IS NULL OR prix_median > 0::numeric),
    CONSTRAINT ck_tarif_commune_prix_median_n_1 CHECK (prix_median_n_1 IS NULL OR prix_median_n_1 > 0::numeric),
    CONSTRAINT ck_tarif_commune_prix_moyen CHECK (prix_moyen IS NULL OR prix_moyen > 0::numeric),
    CONSTRAINT ck_tarif_commune_prix_moyen_n_1 CHECK (prix_moyen_n_1 IS NULL OR prix_moyen_n_1 > 0::numeric),
    CONSTRAINT ck_tarif_commune_transactions CHECK (nombre_transactions >= 0),
    CONSTRAINT ck_tarif_commune_transactions_n_1 CHECK (nombre_transactions_n_1 >= 0),
    CONSTRAINT pk_tarif_commune PRIMARY KEY (id),
    CONSTRAINT tarif_commune_code_insee_not_null NOT NULL code_insee,
    CONSTRAINT tarif_commune_date_calcul_not_null NOT NULL date_calcul,
    CONSTRAINT tarif_commune_date_debut_periode_n_1_not_null NOT NULL date_debut_periode_n_1,
    CONSTRAINT tarif_commune_date_debut_periode_n_not_null NOT NULL date_debut_periode_n,
    CONSTRAINT tarif_commune_date_fin_periode_n_1_not_null NOT NULL date_fin_periode_n_1,
    CONSTRAINT tarif_commune_date_fin_periode_n_not_null NOT NULL date_fin_periode_n,
    CONSTRAINT tarif_commune_id_not_null NOT NULL id,
    CONSTRAINT tarif_commune_nombre_transactions_n_1_not_null NOT NULL nombre_transactions_n_1,
    CONSTRAINT tarif_commune_nombre_transactions_not_null NOT NULL nombre_transactions,
    CONSTRAINT uk_tarif_commune_code_insee UNIQUE (code_insee));


CREATE SEQUENCE IF NOT EXISTS BATCH_STEP_EXECUTION_SEQ
    MAXVALUE 9223372036854775807
    NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS BATCH_JOB_EXECUTION_SEQ
    MAXVALUE 9223372036854775807
    NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS BATCH_JOB_INSTANCE_SEQ
    MAXVALUE 9223372036854775807
    NO CYCLE;
